version:  "3"
services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context:  .  
    image:  lucaspsr/nginx
    container_name:   nginx
    ports:
      - "80:80"
    networks:
      - production-network
    depends_on:
      - "node1"
      - "node2"
      - "node3"
  
  node1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: lucaspsr/alura-books
    container_name: alura-books-1
    ports:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongodb"

  node2:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: lucaspsr/alura-books
    container_name: alura-books-2
    ports:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongodb"

  node3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: lucaspsr/alura-books
    container_name: alura-books-3
    ports:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongodb"

  mongodb:
    image:  mongo
    networks:
      - production-network

networks:
  production-network:
    driver: bridge  
    
